### PR TITLE
DR-763 Remove `yarn` and `npm` lock files and change scripts to use `pnmp`

### PR DESCRIPTION
**Pull request by NamrataSweya**

### CODE REVIEW

**Comment by dmohns** [comment]
You know need to add the Rush lockfile to version control. To do this, you also need to remove this line from `.gitignore` https://github.com/d-rec/drec-origin/blob/DR-763Redundant/.gitignore#L89

**Comment by dmohns** [comment]
Please update this branch with the latest changes from `develop` branch. You can just click this button 
image

**Comment by dmohns** [comment]
Nice, thanks a lot!

Now, one last comment to make this whole change meaningful 😛 

Could you:

- Remove the instructions to install `yarn` from the README it's not longer needed.
- Remove the instructions to run `rush update`. Now that we have a working shrinkwarp file users should not be required to run `rush update` (in fact, they shouldn't)

**Comment by NamrataSweya** [comment]
> Nice, thanks a lot!
> 
> Now, one last comment to make this whole change meaningful 😛
> 
> Could you:
> 
> * Remove the instructions to install `yarn` from the README it's not longer needed.
> * Remove the instructions to run `rush update`. Now that we have a working shrinkwarp file users should not be required to run `rush update` (in fact, they shouldn't)

ok, i make this changes and commit

**Comment by dmohns** [comment]
One last request (apologies I forgot to mention it earlier):

Could you know also do the same in the Github actions CI/CD pipelines? I.e.

- Remove `rush update` step
- Remove `npm i -g yarn`

Everywhere in these two files:

- https://github.com/d-rec/drec-origin/blob/develop/.github/workflows/check.yml
- https://github.com/d-rec/drec-origin/blob/develop/.github/workflows/deploy-gh-pages.yaml

?

**Review by dmohns — APPROVED** [review]
Thank you!!

**Pull request merged**
